default: &default
  adapter: postgresql
  encoding: unicode
  database: ticket
  pool: 5
  host: localhost
  username: breno
  password: leisaj1

development:
  <<: *default
  database: 'ticket'

test:
  <<: *default
  database: 'ticket'

production:
  <<: *default
  database: 'ticket'
